spring:
  security:
    user:
      name: buzz
      password: infinity
  datasource:
    generate-unique-name: false
    name: greenburger

burger:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10


---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN
